import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "./Sections/Footer";
import NavBar from "./Sections/NavBar";

const poppins = Poppins({
  subsets: ["latin"], // or 'latin-ext', based on your needs
  weight: ["400", "600", "700"], // You can select the weights you need
  display: "swap", // For better font rendering performance
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: './favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
